[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "opencv-python>=4.11.0.86",
    "python-docx>=1.1.2",
    "selenium>=4.33.0",
]
